backend/DANG-1104: getWalkDayList 함수에 walkDayIds 인자가 빈 배열일 경우에 대한  예외처리 추가
dangdangwalk/dangdang-walk pull request #769
Opened 2024-06-20 09:36 UTC by opehn

## 작업 내용 (Content)
getWalkDayList 함수에 walkDayIds 인자가 빈 배열일 경우에 대한  예외처리 추가하고
이에 대한 테스트 케이스를 추가했습니다.

## 링크 (Links)

## 기타 사항 (Etc)

## Merge 전 필요 작업 (Checklist before merge)
- [ ] PR 올리기 전 **rebase** 동기화를 하셨나요?
- [ ] 마지막 줄에 공백 처리를 하셨나요?
- [ ] 커밋 단위를 의미 단위로 나눴나요?
    - 예시
        - 코드 가독성을 위해 메서드를 추출하라
        - if-else 문을 if 문으로 분리하라
        - 불필요한 메서드를 인라인화하라
- [ ] 커밋 본문을 작성하셨나요?
    - 예시
        - 함수는 한 가지 일을 해야 한다는 원칙에 따라 메서드를 추출합니다.
        - if-else는 컴파일 시 처리가 되어 재컴파일 없이 수정 할 수 없습니다.  
          이에 따라 코드가 실행되는 순간에 실행이 결정되는 if 문으로 수정합니다.
- [ ] 리뷰 요청 전 Self-Review로 의문점을 해결 하셨나요?
- [ ] PR 리뷰 가능한 크기를 유지하셨나요?
- [ ] CI 파이프라인이 통과가 되었나요?

2024-06-20 10:31 UTC, do0ori requested changes

2024-06-20 10:31 UTC, do0ori commented on backend/src/dog-walk-day/dog-walk-day.service.ts
> +        }
walkDayIds 유효성 체크는 find 전에 하는 것이 좋을 것 같아요.
```suggestion
        if (!walkDayIds.length) {
            this.logger.error(`walkDayIds에 값이 없습니다`, '');
            throw new NotFoundException(`walkDayIds에 값이 없습니다`);
        }
        
        const foundDays = await this.dogWalkDayRepository.find({ where: { id: In(walkDayIds) } });
```

2024-06-20 10:31 UTC, do0ori commented on backend/src/dog-walk-day/dog-walk-day.service.spec.ts
>          });
context-it 구조로 작성해야 할 것 같아요.
`context('빈 배열이 주어지면') ~ it('NotFoundException 예외를 던져야 한다.')`
`context('존재하지 않는 id가 포함된 배열이 주어지면') ~ it('NotFoundException 예외를 던져야 한다.')`

2024-06-20 10:42 UTC, opehn commented on backend/src/dog-walk-day/dog-walk-day.service.ts
> +        }
헉 왜 이렇게 했지ㅋㅋ 고칠게요

2024-06-20 16:30 UTC, do0ori approved these changes

2024-06-21 04:41 UTC, jihwooon approved these changes

2024-06-21 05:50 UTC, merged