backend/DANG-1118: profiligInterceptor 리턴 전 profile 히스토리를 삭제하도록 변경
dangdangwalk/dangdang-walk pull request #783
Opened 2024-06-23 12:18 UTC by opehn

- profile history가 남아있어 이전 호출시 실행되었던 쿼리에 대한 profile 까지 중복으로 기록되는 문제가 있었습니다. 
- 인터셉터 리턴 전에 히스토리를 초기화하도록 변경하였습니다.

## 작업 내용 (Content)

## 링크 (Links)

## 기타 사항 (Etc)

## Merge 전 필요 작업 (Checklist before merge)
- [ ] PR 올리기 전 **rebase** 동기화를 하셨나요?
- [ ] 마지막 줄에 공백 처리를 하셨나요?
- [ ] 커밋 단위를 의미 단위로 나눴나요?
    - 예시
        - 코드 가독성을 위해 메서드를 추출하라
        - if-else 문을 if 문으로 분리하라
        - 불필요한 메서드를 인라인화하라
- [ ] 커밋 본문을 작성하셨나요?
    - 예시
        - 함수는 한 가지 일을 해야 한다는 원칙에 따라 메서드를 추출합니다.
        - if-else는 컴파일 시 처리가 되어 재컴파일 없이 수정 할 수 없습니다.  
          이에 따라 코드가 실행되는 순간에 실행이 결정되는 if 문으로 수정합니다.
- [ ] 리뷰 요청 전 Self-Review로 의문점을 해결 하셨나요?
- [ ] PR 리뷰 가능한 크기를 유지하셨나요?
- [ ] CI 파이프라인이 통과가 되었나요?

2024-06-23 13:06 UTC, jihwooon approved these changes

2024-06-23 13:27 UTC, do0ori requested changes

2024-06-23 13:27 UTC, do0ori commented on backend/src/common/interceptors/profilingInterceptor.ts
> +        await this.dataSource.query('SET profiling_history_size = 1000');
`profiling_history_size`를 설정하는 것과 `profiling` 설정은 독립적이어서 여기서 `SET profiling = 0`을 할 필요는 없을 것 같아요.
또 mysql 공식 문서에 따르면 profiling_history_size의 최댓값은 100이라고 하네요.
> - [profiling_history_size](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_profiling_history_size)
The number of statements for which to maintain profiling information if [profiling](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_profiling) is enabled. The default value is 15. **_The maximum value is 100._** Setting the value to 0 effectively disables profiling. See [Section 15.7.7.32, “SHOW PROFILES Statement”](https://dev.mysql.com/doc/refman/8.4/en/show-profiles.html).
```suggestion
        await this.dataSource.query('SET profiling_history_size = 100');
```

2024-06-23 13:27 UTC, do0ori commented on backend/src/common/interceptors/profilingInterceptor.ts
> -                            switchMap(() => from(this.dataSource.query('SET profiling = 0'))),
요청이 끝날 때 profiling은 disable해줘야 profiling을 사용하지 않을 때에도 영향이 없을 것 같아요.
[profiling의 경우 세션 변수](https://dev.mysql.com/doc/refman/8.4/en/show-profile.html)인데 요청을 보낼 때마다 세션을 만드는 거라면 매 세션마다 profiling = 0으로 초기화되어 문제가 없겠지만, typeorm은 default로 connection pool을 사용하기 때문에 세션을 재사용해요.

2024-06-23 13:55 UTC, do0ori commented on backend/src/common/interceptors/profilingInterceptor.ts
> -                            switchMap(() => from(this.dataSource.query('SET profiling = 0'))),
```
        return from(this.initProfiling()).pipe(
            switchMap(() => {
                const now = Date.now();
                return next
                    .handle()
                    .pipe(finalize(() => from(this.logProfilingData(method, originUrl, now)).subscribe()));
            }),
        );
```

2024-06-23 14:53 UTC, opehn commented on backend/src/common/interceptors/profilingInterceptor.ts
> -                            switchMap(() => from(this.dataSource.query('SET profiling = 0'))),
음.. 찾아보니까 finalize를 쓰면 좋을것같은데, 
히스토리 초기화하는 로직을 finalize 하는걸 생각했는데 쓰신 코드에는 로깅하는 부분이 되어있네요
일단 제가 고친대로 커밋 올려볼게요
가드에서 걸려도 히스토리 안찍히는건 확인했어요
추가 수정사항이 있으면 코멘트 달아주세요

2024-06-23 20:00 UTC, do0ori approved these changes

2024-06-24 03:17 UTC, do0ori requested changes

2024-06-24 03:17 UTC, do0ori commented on backend/src/common/interceptors/profilingInterceptor.ts
> -                            switchMap(() => from(this.dataSource.query('SET profiling = 0'))),
지금 e2e test가 통과가 안되네요 finalize 때문인 것 같아요

2024-06-24 03:20 UTC, opehn commented on backend/src/common/interceptors/profilingInterceptor.ts
> -                            switchMap(() => from(this.dataSource.query('SET profiling = 0'))),
어 아까 말했던 update 문제 아닌가요? 저는 그것만 뜨는데

2024-06-24 03:25 UTC, merged